### PR TITLE
Static code analyzer

### PR DESCRIPTION
**Pull request by TonisOrmisson**
Targeting v1.6 with php >= 7.4

added the phpstan static code analyzer to dependencies and github actions. 
fixed the code to pass phpstan on level 1 at this point

possibly pushing more level passes here if not merged first ...

### CODE REVIEW

**Comment by maxxer** [comment]
Thanks. Does it supersede PHP-CS-Fixer? #460

**Comment by TonisOrmisson** [comment]
@maxxer 
I haven't used CS-fixer, but from I understand they are a bit different and I see no problem having them both. phpstan will only analyze, it will not fix anything by itself. PHP-CS-fixer is more of a automatic fixer tool rather than analyzer. 

I have attached the `$vendor/bin/phpstan analyze` command also to the github actions after running tests, so also if some sh!**y code is posted it will fail the CI pipeline also based on code quality and refer to the exact faulty lines that should be fixed to standards to keep the code in good shape also after changes. 

Currently clean on level 1 of 9 (0..9). 
level 2 indicates 172 more issues
level 5 indicates 243 more issues
level 9 indicates 939 more issues

most probably running cs-fixer will resolve a part of them but surely not most of them

**Comment by maxxer** [comment]
I'll merge the pending patches for 1.6 and then run cs-fixer again to see what is the result

**Comment by maxxer** [comment]
Your patch hit hard 🤣

**Comment by TonisOrmisson** [comment]
I will fix the current code to pass and make a pr

**Comment by maxxer** [comment]
I'm fixing the translation file issues

**Comment by TonisOrmisson** [comment]
im already done :)

**Pull request merged**
