### PR TITLE
Fix French translation

### PR DESCRIPTION
**Pull request by arollmann**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Fixed issues  |# fixed by the PR

### CODE REVIEW

**Comment by maxxer** [comment]
Woud you please add a note to the changelog? there's already a line for the french translation, add yourself. thanks

**Comment by arollmann** [comment]
OK, done.

**Comment by maxxer** [comment]
Please close the other PR and add a commit to this one. Thanks

**Comment by arollmann** [comment]
Oh yes, sorry.  It's done.

**Comment by maxxer** [comment]
thanks

**Pull request merged**
