### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by bizley**
Polish translation

### CODE REVIEW

**Comment by tonydspaniard** [comment]
Thank you @bizley! 

Do you mind adding your name with this enhancement to the changelog file? On another note, I have included two-factor authentication to the module but didn't update the translations yet. The translation may be missing a couple of sentences from master.

**Comment by bizley** [comment]
Sure thing, give me few minutes

**Comment by bizley** [comment]
Done.

I've noticed you have got some of the translation string concatenated with dot. This might not get caught by translation exporter (I've added full string to Polish translations as well).

https://github.com/2amigos/yii2-usuario/blob/master/src/User/Strategy/SecureEmailChangeStrategy.php#L50-L51
https://github.com/2amigos/yii2-usuario/blob/master/src/User/Service/EmailChangeService.php#L65-L66
https://github.com/2amigos/yii2-usuario/blob/master/src/User/Service/EmailChangeService.php#L75-L76

**Comment by tonydspaniard** [comment]
Oh man! What a silly mistake I did. I'll fix them asap. Thanks @bizley

**Comment by tonydspaniard** [comment]
@bizley I have fixed the translation messages (thanks) and updated the repo. Some statements are missing on your message file. If you have time, would be awesome if you could update them.

**Pull request merged**
