### PR TITLE
#115 Convert client_id to string because pgsql fail with type convertion

### PR DESCRIPTION
**Pull request by Dezinger**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #115

### CODE REVIEW

**Comment by tonydspaniard** [comment]
Mind adding this fix on to the CHANGELOG file? Thanks!

**Comment by Dezinger** [comment]
Done

**Comment by tonydspaniard** [comment]
:(

**Comment by Dezinger** [comment]
it's ok ;)

**Comment by tonydspaniard** [comment]
Thank you so much @Dezinger. Appreciated the use of your free time to improve the library.

**Pull request merged**
