### PR TITLE
Fixes bug 2amigos#384 and allows the flash message to be disabled in …

### PR DESCRIPTION
**Pull request by cgsmith**
Deletes flash message after being consumed by the partial view

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes (minor?)
| Tests pass?   | yes
| Fixed issues  | #384

### CODE REVIEW

**Comment by maxxer** [comment]
I'll have a look, thanks.

**Comment by maxxer** [comment]
I'm not really sure this is the best approach. As per docs the `enableFlashMessages` is doing the same, except for a small change I did in the past which could have been a mistake. If you grep for `setFlash` there are tons of them, but only a very few are checked for that param. This patch would make minimal difference.

Let's discuss this on the issue

**Comment by cgsmith** [comment]
@maxxer updated with delete for flash message.

Technically breaks BC but it was a bug? So? Fixes? heh

**Comment by maxxer** [comment]
I'm ok with merge, indeed can be a problem, I'll try to make it pretty clear in the changelog. I wonder what could be a use case when deleting flash messages after display can be a problem.

I'm asking you one more thing: please fix changelog and also add a comment into docs explaining that disabling the param is useful when handling messages in your own views, as it's stated in Module.php.

Thanks

**Comment by cgsmith** [comment]
@maxxer understood.

**Comment by cgsmith** [comment]
@maxxer I updated the comment. pulled from master but i am not sure why so many other commits came through. I can make a new PR if this one is too messed up.

Thanks for your patience and review.

**Comment by maxxer** [comment]
merged

**Comment by maxxer** [comment]
sorry @cgsmith, I did something wrong when squashing the merge and I wiped your authoring. It remains the credit in the changelog 😅

**Pull request closed without merging**
