### PR TITLE
Always create flash messages, allow `enableFlashMessages` only to dictate display (#391)

### PR DESCRIPTION
**Pull request by ajmedway**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #391

### CODE REVIEW

**Comment by maxxer** [comment]
Thanks for the PR! Unfortunately this breaks a lot of tests, they need to be updated with the correct conditions!

**Comment by ajmedway** [comment]
> Thanks for the PR! Unfortunately this breaks a lot of tests, they need to be updated with the correct conditions!

The issues do not seem to stem from my changes?

**Comment by maxxer** [comment]
I see, I'll have a look thanks

**Comment by maxxer** [comment]
Thank you for the changes. I'd like to sort it out for good, that is address *all* concerns raised by the issue (included [this](https://github.com/2amigos/yii2-usuario/commit/53209d2d78530c8ba0698cbcd170c1919fed0c41#r34440185)), in order to avoid introducing further confusion.

**Comment by ajmedway** [comment]
Hello, I have made a fresh merge from upstream master, can this PR now be merged? All checks have passed.

Many thanks, Alec

**Comment by ajmedway** [comment]
> I'd like to sort it out for good, that is address all concerns raised by the issue (included [this](https://github.com/2amigos/yii2-usuario/commit/53209d2d78530c8ba0698cbcd170c1919fed0c41#r34440185))

Pretty sure this PR does address this concern

**Pull request merged**
