### PR TITLE
re #224 add option to require consent

### PR DESCRIPTION
**Pull request by tonydspaniard**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #224

### CODE REVIEW

**Comment by tonydspaniard** [comment]
@maxxer mind reviewing?

**Comment by tonydspaniard** [comment]
If merged we will require to update the translations prior to launch new version?

**Comment by maxxer** [comment]
Sorry I haven't replied yet, looks ok at first sight. I will try to do a proper testing next week

**Comment by tonydspaniard** [comment]
@maxxer tests need to be fixed... I'll do when you have time to review it.

**Pull request merged**
