### PR TITLE
New response from google api

### PR DESCRIPTION
**Pull request by Julian-B90**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #316

### CODE REVIEW

**Comment by tonydspaniard** [comment]
Mind adding your fix to our changelog file? I'll merge

**Comment by Julian-B90** [comment]
I would like to do that :-D

**Comment by Julian-B90** [comment]
@tonydspaniard i have made a entry in the changelog. Is this correct?

**Comment by tonydspaniard** [comment]
@Julian-B90 yes sir!

**Pull request merged**
