### PR TITLE
Added option to restrict user assignments to roles only

### PR DESCRIPTION
**Pull request by CheckeredFlag**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | n/a
| Fixed issues  | #324

### CODE REVIEW

**Comment by tonydspaniard** [comment]
Thanks!

**Comment by checkeredflag** [comment]
I have no idea how to interpret the failing test and whether it's unrelated.

**Comment by maxxer** [comment]
> I have no idea how to interpret the failing test and whether it's unrelated.

php7.4 is still in beta, we probably should change it to a failable test. it's ok

**Comment by maxxer** [comment]
I'm ok with the changes. 

It would be great to have visual difference between roles and permissions, if you have time ;)

**Comment by checkeredflag** [comment]
> I'm ok with the changes.
> 
> It would be great to have visual difference between roles and permissions, if you have time ;)

I included `optgroup` as part this PR.  Is that sufficient?

**Comment by maxxer** [comment]
Indeed I didn't notice it. Looks ok to me

**Comment by CheckeredFlag** [comment]
Is there anything that is preventing this PR from being merged - besides free time?  Just wanted to ensure you weren't waiting on me for something.

**Comment by maxxer** [comment]
I'm ok with it. If @tonydspaniard has nothing against we can merge

**Comment by tonydspaniard** [comment]
I am also ok, could you check whether the error on travis is due to your change?

**Pull request merged**
