### PR TITLE
Allow parent-child relationship to permissions

### PR DESCRIPTION
**Pull request by Philosoft**
It's even in [the guide](http://www.yiiframework.com/doc-2.0/guide-security-authorization.html#rbac) <kbd>ctrl</kbd>+<kbd>f</kbd> `updateownpost`

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | wasn't launched
| Fixed issues  | afaik none

### CODE REVIEW

**Comment by tonydspaniard** [comment]
@Philosoft please, add the change on the Change log 🍺

**Comment by Philosoft** [comment]
done :)

**Comment by tonydspaniard** [comment]
@Philosoft you forgot your name... :) but i'll merge it

**Comment by tonydspaniard** [comment]
Thank you!

**Pull request merged**
