### PR TITLE
Ru fixes

### PR DESCRIPTION
**Pull request by Katenkka**
Hello, I updated Russian translation.

### CODE REVIEW

**Comment by tonydspaniard** [comment]
Hi @Katenkka ! 

Thank you very much for your help. There is one #88 that I am about to merge where @kartik-v has updated the translations. Do you think that you will be able to update it afterwards?

**Comment by tonydspaniard** [comment]
Dear @Katenkka I have merged #88 would be awesome if you could update your branch and translations to match new additions. 

Thank you very much for spending time on this project.

**Comment by Katenkka** [comment]
Yes, sure, no problem. I updated my branch.

**Comment by tonydspaniard** [comment]
Thanks!

**Pull request merged**
