### PR TITLE
Fix for issue #34

### PR DESCRIPTION
**Pull request by tekord**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes/no
| Fixed issues  | #34

### CODE REVIEW

**Comment by tekord** [comment]
I accidentally added some commits which are not related to the original issue #34. I do not know very well how PR works, still learning.

**Comment by tonydspaniard** [comment]
I really appreciate that you have spend some time to do the PRs. But I really need to understand why you wish to have the ability to modify their internal translations? 

IMO is much simpler to override the views (we do that) and provide my own `app` translations where `usuario` don't have.

**Comment by tekord** [comment]
Let's say some team installed module for their project and didn't find translations for their native language. What should they do then? They can do fork of usuario and update the messages for their native language (they need to fork because it is bad to edit files inside vendor folder). But in my opition it is much faster to copy usuario's dictionary file into the project and redirect module's translation base path to the project's translation path, like I did yesterday for my project. What do you think?

**Comment by tonydspaniard** [comment]
@tekord the only thing they need to do is to update the files and create a PR: https://github.com/2amigos/yii2-usuario/tree/master/src/User/resources/i18n , then the PR will get merged.

That is the standard way for all libraries. Why would you do the translations for your own software and not provide the translations for it?

**Comment by tekord** [comment]
> thing they need to do is to update the files and create a PR
> Why would you do the translations for your own software and not provide the translations for it?

I am not saying about not provide the translations as PR, I saying about speed of working. If right now I need to provide translations for application and my client is awaiting I can't spend time to make PR and wait while library will be updated. It may took hours or days.

**Comment by tonydspaniard** [comment]
> I am not saying about not provide the translations as PR, I saying about speed of working. If right > now I need to provide translations for application and my client is awaiting I can't spend time to > make PR and wait while library will be updated. It may took hours or days.

The way to do it then is overriding the views and use your very own translations (ie `Yii::t('app', 'Your translation');`)

**Pull request closed without merging**
