### PR TITLE
#119 Security fix: add AccessControl to RuleController

### PR DESCRIPTION
**Pull request by Dezinger**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
|Issue|#119

### CODE REVIEW

**Comment by tonydspaniard** [comment]
@Dezinger Please, add this fix on CHANGELOG and I'll happily merge all your three PRs. Thanks!

**Comment by Dezinger** [comment]
im glad to help thanks

**Comment by tonydspaniard** [comment]
I tried to resolve conflicts but it doesn't allow me... apologies

**Comment by Dezinger** [comment]
ok resolved

**Comment by Dezinger** [comment]
i think will be one more conflict
i fix it then

**Pull request merged**
