### PR TITLE
Fix string: Two factor authentication protects (against -> in case of) stolen credentials

### PR DESCRIPTION
**Pull request by TonisOrmisson**
As discussed here:
https://github.com/2amigos/yii2-usuario/commit/19eb9df623063f9afc3959dfded53c7bf59f1f4d#commitcomment-29750159

Use "in case of" instead of "against" in string  "Two factor authentication protects you against stolen credentials"

### CODE REVIEW

**Comment by tonydspaniard** [comment]
@TonisOrmisson Thank you so much for your contribution and time to this project. I think this PR, should be on hold till all translations are done. 

Then update, and wait for the contributors to make modifications if any. What do you think?

**Comment by TonisOrmisson** [comment]
Yes, sure! Thanks

**Comment by tonydspaniard** [comment]
@TonisOrmisson I think now is a good time ;)

**Comment by tonydspaniard** [comment]
@TonisOrmisson @maxxer seems we missed again some translations :(

**Comment by maxxer** [comment]
unfortunately yes, I've failed in releasing early...

**Comment by tonydspaniard** [comment]
@maxxer @TonisOrmisson can we merge this already?

**Comment by TonisOrmisson** [comment]
I don't see any reason why not.

**Comment by maxxer** [comment]
👍

**Pull request merged**
