### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by ajmedway**

### CODE REVIEW

**Comment by maxxer** [comment]
In the future, you don't need to make a new PR for changes relative to an existing one! You can still commit and push to the same branch and they will make their way together.

**Comment by ajmedway** [comment]
I am a Bitbucket/Sourcetree user normally - I very rarely use Github and not so familiar. I created a Pull Request but didn't see any way to add extra files to the PR - how do I do this on here?

**Comment by ajmedway** [comment]
@maxxer 
> You can still commit and push to the same branch and they will make their way together.

This is all I see - where do I initiate the push?

image

**Comment by maxxer** [comment]
Just as you did in #147, commit and push to the same branch

**Comment by tonydspaniard** [comment]
Thank you @maxxer. 

Yes @ajmedway you simply make a new commit to the same PR the change will be shown.

**Pull request merged**
