### PR TITLE
Issue #49 fix | make() should pass attributes as third parameter

### PR DESCRIPTION
**Pull request by MKiselev**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #49

### CODE REVIEW

**Comment by MKiselev** [comment]
I'm sorry, but I can't provide tests. :(

**Comment by tonydspaniard** [comment]
@MKiselev is all fine... do you mind resolving the conflicts? I'll be happy to merge

**Comment by tonydspaniard** [comment]
@MKiselev do not worry... I have to do all the missing tests yet. Thank you for your work on the module. Very kind of you to spend time fixing bugs.

**Comment by MKiselev** [comment]
@tonydspaniard I like concepts in this module 👍 .

Can you release minor version?

**Comment by tonydspaniard** [comment]
@MKiselev will do...

**Comment by tonydspaniard** [comment]
@MKiselev minor version released

**Comment by MKiselev** [comment]
@tonydspaniard thanks 👍

**Pull request merged**
