### PR TITLE
Add controller module class reference

### PR DESCRIPTION
**Pull request by TonisOrmisson**
added the reference to controllers using User Module properties for simpler IDE usage

### CODE REVIEW

**Comment by maxxer** [comment]
Why you want to implement this change? Also why not AdminController, which still uses `$this->module`?

**Comment by TonisOrmisson** [comment]
Why?
I was just going through some files looking at IDE warnings regarding inconsistencies. All of the changed controllers actually use some properties of the `\Da\User\Module` so it just links the usages with the actual source and makes it easier for automated code reading.

Why not AdminController?
Because there is no usage of the module properties that are not documented. There is a usage, but its documented in-line. I could also switch that for Class documentation instead?

**Comment by tonydspaniard** [comment]
There is a trait for that purpose `ModuleAwareTrait`

**Comment by TonisOrmisson** [comment]
Well of course, thanks for reminding :)

**Comment by tonydspaniard** [comment]
@TonisOrmisson do you mind adding your enhancement to the CHANGELOG? I really dislike to not give credit who spent their precious time on the library.

This enhancement doesn't hurt @maxxer I am fiine with adding it whilst using already created classes (trait)

**Pull request merged**
