### PR TITLE
Check enableEmailConfirmation

### PR DESCRIPTION
**Pull request by faenir**
Show different flash messages, depending on enableEmailConfirmation is enabled or not.

### CODE REVIEW

**Comment by tonydspaniard** [comment]
Thanks @faenir if its a new message, we should run the `.yii message extract` command again and update translation files.

**Comment by faenir** [comment]
@tonydspaniard its not new message:
https://github.com/2amigos/yii2-usuario/blob/51c9c9a30fc0e236883ff8959f8eb98211518caa/src/User/Controller/RegistrationController.php#L120

**Comment by tonydspaniard** [comment]
@faenir Thanks for pointing that out. Please, fix the test issues (is related to the message), add your self to the credit line at the CHANGELOG with this enhancement, and I'll be very happy to merge. 

Thanks for your time and work.

**Comment by faenir** [comment]
@tonydspaniard tests fixed. Changelog update: #156 (don't know how to add commit to the current PR, merge it, if you can please).

**Pull request merged**
