### PR TITLE
Add UserBlockService to Bootstrap build class map

### PR DESCRIPTION
**Pull request by AndreScara11**
Added UserBlockService in the build class map to be able to overwrite it

### CODE REVIEW

**Comment by AndreScara11** [comment]
It seems that many others classes are missing in the class map, maybe it's worth opening an issue?

**Comment by TonisOrmisson** [comment]
Why not use the DI contauiner instead of classMap? Should also be probably workable for the "other" classes. 
UserBlockService is injected as a dependency in Yii's internal container and created only via ->make(), getting the dependency from container. So you can just set your own custom class to DI container after loading this module and you should be good to go with nothing added to classMap

**Comment by maxxer** [comment]
I remember I used DI in the past for classes overload. @mp1509 if you feel some classes are missing here, please add them to the PR so we have a consistent behaviour.

**Comment by AndreScara11** [comment]
I added more classes to the classMap, not all, only those of the folders already present

**Pull request merged**
