### PR TITLE
Implement and document database migration command [issue #172]

### PR DESCRIPTION
**Pull request by tsdogs**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #172

please review and comment.
I have tested it on my projects and seems to be working fine.

### CODE REVIEW

**Comment by tonydspaniard** [comment]
I need to check all this... Sorry for my late response. Currently highly busy @tsdogs

**Comment by tsdogs** [comment]
I didn't know about migration/mark 
seems to be a good solution (simply document it in the migration guide)

**Comment by tsdogs** [comment]
Yes, I need to migrate a few projects in the near future so I'll write down the procedure.

**Comment by tsdogs** [comment]
this should be superseded by #192

**Comment by maxxer** [comment]
closing per above command

**Pull request closed without merging**
